import { NextResponse } from 'next/server'

// GET all available AI providers
export async function GET() {
  const providers = [
    {
      id: 'openai',
      name: 'OpenAI',
      description: 'GPT-4, GPT-4-turbo, GPT-3.5-turbo',
      models: ['gpt-4', 'gpt-4-turbo', 'gpt-3.5-turbo', 'gpt-4o', 'gpt-4o-mini'],
      requiresApiKey: true,
      website: 'https://platform.openai.com',
      category: 'cloud',
    },
    {
      id: 'anthropic',
      name: 'Anthropic',
      description: 'Claude 3.5 Sonnet, Claude 3 Opus, Claude 3 Haiku',
      models: ['claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
      requiresApiKey: true,
      website: 'https://console.anthropic.com',
      category: 'cloud',
    },
    {
      id: 'google',
      name: 'Google AI',
      description: 'Gemini 1.5 Pro, Gemini 1.5 Flash, Gemini Pro',
      models: ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-pro', 'gemini-pro-vision'],
      requiresApiKey: true,
      website: 'https://ai.google.dev',
      category: 'cloud',
    },
    {
      id: 'groq',
      name: 'Groq',
      description: 'Lightning-fast inference',
      models: ['mixtral-8x7b-32768', 'llama2-70b-4096', 'gemma-7b-it', 'llama-3.1-70b-versatile'],
      requiresApiKey: true,
      website: 'https://groq.com',
      category: 'cloud',
    },
    {
      id: 'mistral',
      name: 'Mistral AI',
      description: 'Mistral 7B, 8x7B models',
      models: ['mistral-medium-latest', 'mistral-small-latest', 'mixtral-8x7b-instruct', 'mistral-7b-instruct'],
      requiresApiKey: true,
      website: 'https://mistral.ai',
      category: 'cloud',
    },
    {
      id: 'cohere',
      name: 'Cohere',
      description: 'Command R, Command R+',
      models: ['command-r', 'command-r-plus', 'command', 'command-nightly'],
      requiresApiKey: true,
      website: 'https://cohere.ai',
      category: 'cloud',
    },
    {
      id: 'together',
      name: 'Together AI',
      description: 'Open source models',
      models: ['meta-llama/Llama-2-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO'],
      requiresApiKey: true,
      website: 'https://together.xyz',
      category: 'cloud',
    },
    {
      id: 'perplexity',
      name: 'Perplexity',
      description: 'Web-enhanced models',
      models: ['llama-3-sonar-small-128k-online', 'llama-3-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
      requiresApiKey: true,
      website: 'https://perplexity.ai',
      category: 'cloud',
    },
    {
      id: 'huggingface',
      name: 'Hugging Face',
      description: 'Thousands of open models',
      models: ['microsoft/DialoGPT-large', 'facebook/blenderbot-400M-distill', 'meta-llama/Llama-2-70b-hf'],
      requiresApiKey: true,
      website: 'https://huggingface.co',
      category: 'cloud',
    },
    {
      id: 'openrouter',
      name: 'OpenRouter',
      description: 'Unified API for multiple models',
      models: ['openai/gpt-4', 'anthropic/claude-3-sonnet', 'meta-llama/llama-2-70b-chat', 'google/gemini-pro'],
      requiresApiKey: true,
      website: 'https://openrouter.ai',
      category: 'cloud',
    },
    {
      id: 'moonshot',
      idAlt: 'kimi',
      name: 'Moonshot AI',
      description: 'Chinese language models',
      models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
      requiresApiKey: true,
      website: 'https://platform.moonshot.cn',
      category: 'cloud',
    },
    {
      id: 'hyperbolic',
      name: 'Hyperbolic',
      description: 'Open source inference',
      models: ['meta-llama/Llama-2-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
      requiresApiKey: true,
      website: 'https://hyperbolic.xyz',
      category: 'cloud',
    },
    {
      id: 'xai',
      name: 'xAI',
      description: 'Grok beta, Grok vision by Elon Musk',
      models: ['grok-beta', 'grok-vision-beta', 'grok-2'],
      requiresApiKey: true,
      website: 'https://x.ai',
      category: 'cloud',
    },
    {
      id: 'deepseek',
      name: 'DeepSeek',
      description: 'Advanced code and chat models',
      models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
      requiresApiKey: true,
      website: 'https://platform.deepseek.com',
      category: 'cloud',
    },
    {
      id: 'github',
      name: 'GitHub Models',
      description: 'Microsoft GitHub Models',
      models: ['gpt-4', 'claude-3-sonnet', 'llama-3-70b', 'gpt-3.5-turbo'],
      requiresApiKey: true,
      website: 'https://github.com/marketplace/models',
      category: 'cloud',
    },
    {
      id: 'novita',
      name: 'Novita AI',
      description: 'Fast and affordable inference',
      models: ['meta-llama/Llama-2-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
      requiresApiKey: true,
      website: 'https://novita.ai',
      category: 'cloud',
    },
    {
      id: 'ai21',
      name: 'AI21',
      description: 'Jurassic models',
      models: ['j1-large', 'j1-grande', 'j2-large', 'j2-grande'],
      requiresApiKey: true,
      website: 'https://www.ai21.com',
      category: 'cloud',
    },
    {
      id: 'replicate',
      name: 'Replicate',
      description: 'Open source model predictions',
      models: ['ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4', 'meta/meta-llama-3-8b-instruct'],
      requiresApiKey: true,
      website: 'https://replicate.com',
      category: 'cloud',
    },
    {
      id: 'fireworks',
      name: 'Fireworks AI',
      description: 'High-performance inference',
      models: ['accounts/fireworks/models/llama-v2-70b-chat', 'accounts/fireworks/models/mixtral-8x7b-instruct-v0.1'],
      requiresApiKey: true,
      website: 'https://fireworks.ai',
      category: 'cloud',
    },
    {
      id: 'ollama',
      name: 'Ollama',
      description: 'Run AI models locally',
      models: ['llama2', 'codellama', 'mistral', 'phi3', 'qwen', 'falcon', 'wizardlm'],
      requiresApiKey: false,
      website: 'https://ollama.ai',
      category: 'local',
    },
    {
      id: 'lmstudio',
      name: 'LM Studio',
      description: 'Local model interface',
      models: ['local-model', 'ggml', 'gguf'],
      requiresApiKey: false,
      website: 'https://lmstudio.ai',
      category: 'local',
    },
    {
      id: 'bedrock',
      name: 'AWS Bedrock',
      description: 'Amazon Web Services Bedrock',
      models: ['anthropic.claude-v2', 'anthropic.claude-instant-v1', 'anthropic.claude-3-sonnet', 'anthropic.claude-3-haiku'],
      requiresApiKey: true,
      website: 'https://aws.amazon.com/bedrock',
      category: 'cloud',
    },
  ]

  return NextResponse.json(providers)
}
